name: workflow

on:
  push:
  schedule:
    - cron: '0 0 * * 1'  # run every Monday

jobs:
  workflow-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windowsGPU]
    defaults:
      run:
        shell: cmd /C CALL {0}

    steps:
    - name: Initialisation
      uses: actions/checkout@v2

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        activate-environment: conda-environment
        environment-file: .github/environment.yml


    - name: Install invoke
      run: python -m pip install invoke

    - name: Install package
      run: python -m pip install .[dev]

    - name: Unit tests
      run: python -m pytest -v mumax3c

    - name: Unit tests
      run: invoke test.unittest
#      if: matrix.os != 'ubuntu-latest'

#    - name: Unit tests with coverage
#      run: invoke test.coverage
#      if: matrix.os == 'ubuntu-latest'

    - name: Documentation tests
      run: invoke test.docs

    - name: Jupyter notebook tests
      run: invoke test.ipynb

#    - name: Upload coverage to Codecov.io
#      uses: codecov/codecov-action@v1
#      if: matrix.os == 'ubuntu-latest'

  workflow-linux:
    runs-on: linuxGPU
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Initialisation
      uses: actions/checkout@v2

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: conda-environment
        environment-file: .github/environment.yml

    - name: Install invoke
      run: python -m pip install invoke

    - name: Install package
      run: python -m pip install .[dev]

    - name: Unit tests
      run: python -m pytest -v mumax3c

    - name: Unit tests
      run: invoke test.unittest
#      if: matrix.os != 'ubuntu-latest'

#    - name: Unit tests with coverage
#      run: invoke test.coverage
#      if: matrix.os == 'ubuntu-latest'

    - name: Documentation tests
      run: invoke test.docs

    - name: Jupyter notebook tests
      run: invoke test.ipynb

#    - name: Upload coverage to Codecov.io
#      uses: codecov/codecov-action@v1
#      if: matrix.os == 'ubuntu-latest'
