name: workflow

on:
  push:
  schedule:
    - cron: '0 0 * * 1'  # run every Monday

jobs:
  workflow-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windowsGPU]
    defaults:
      run:
        shell: powershell {0}

    steps:
    - name: Initialisation
      uses: actions/checkout@v2

    - name: Create conda env
      run: conda create -n test-env -c conda-forge -y python==3.8 pip

    - name: Install packages
      run: |
        # eval "$(conda shell.bash hook)"
        conda activate test-env
        conda env list
        python --version
        python -m pip install invoke
        python -m pip install git+https://github.com/ubermag/ubermagutil.git
        python -m pip install git+https://github.com/ubermag/ubermagtable.git
        python -m pip install git+https://github.com/ubermag/discretisedfield.git
        python -m pip install git+https://github.com/ubermag/micromagneticmodel.git
        python -m pip install git+https://github.com/ubermag/micromagnetictests.git
        python -m pip install .[dev]

    - name: Unit tests with coverage
      run: |
        # eval "$(conda shell.bash hook)"
        conda activate test-env
        invoke test.coverage

    - name: Doc tests
      run: |
        # eval "$(conda shell.bash hook)"
        conda activate test-env
        invoke test.docs

    - name: Notebook tests
      run: |
        # eval "$(conda shell.bash hook)"
        conda activate test-env
        invoke test.ipynb

    - name: Remove conda env
      run: conda env remove -n test-env
      if: always()

    - name: Upload coverage to Codecov.io
      uses: codecov/codecov-action@v1

  workflow-linux:
    runs-on: linuxGPU
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Initialisation
      uses: actions/checkout@v2

    - name: Create conda env
      run: conda create -n test-env -c conda-forge -y python==3.8 pip

    - name: Install packages
      run: |
        eval "$(conda shell.bash hook)"
        conda activate test-env
        python --version
        python -m pip install invoke
        python -m pip install git+https://github.com/ubermag/ubermagutil.git
        python -m pip install git+https://github.com/ubermag/ubermagtable.git
        python -m pip install git+https://github.com/ubermag/discretisedfield.git
        python -m pip install git+https://github.com/ubermag/micromagneticmodel.git
        python -m pip install git+https://github.com/ubermag/micromagnetictests.git
        python -m pip install .[dev]

    - name: Unit tests with coverage
      run: |
        eval "$(conda shell.bash hook)"
        conda activate test-env
        invoke test.coverage

    - name: Doc tests
      run: |
        eval "$(conda shell.bash hook)"
        conda activate test-env
        invoke test.docs

    - name: Notebook tests
      run: |
        eval "$(conda shell.bash hook)"
        conda activate test-env
        invoke test.ipynb

    - name: Remove conda env
      run: conda env remove -n test-env
      if: always()

    - name: Upload coverage to Codecov.io
      uses: codecov/codecov-action@v1
